# Site Settings
locale                   : "en-UK"
title                    : "TWSH / Website"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Tobias Slade-Harajda"
description              : "3rd Year Ph.D. student"
url                      : https://tobiassh0.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
words_per_minute         : 200
theme                    : jekyll-theme-minimal
show_downloads           : true

#title: TWSH / Website
#name: Tobias Slade-Harajda
#logo: /assets/img/logo.png
#description: 3rd year Ph.D. student
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
#location: University of Warwick
#

