# Site Settings
title : TWSH / Website
author:
    name : Tobias Slade-Harajda
    email : tobias.slade-harajda@warwick.ac.uk
description : 3rd Year Ph.D. student at the University of Warwick
logo : /assets/img/profile.png
locale : "en-UK"
title_separator : "-"
subtitle : # site tagline that appears below site title in masthead
url : https://tobiassh0.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
words_per_minute : 200
theme : jekyll-theme-minimal
#show_downloads : true
linkedin : "https://www.linkedin.com/in/tobias-slade-harajda-50a496192/"
orcid : "https://orcid.org/0000-0002-4993-0757"
include :
  - _pages


#show_downloads: true
#google_analytics:
#location: University of Warwick

