# Site Settings
title : TWSH / Website
author:
    name : Tobias Slade-Harajda
    email : tobias.slade-harajda@warwick.ac.uk
description : 3rd Year Ph.D. student
logo : /assets/img/logo.png
locale : "en-UK"
title_separator : "-"
subtitle : # site tagline that appears below site title in masthead
url : https://tobiassh0.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
words_per_minute : 200
theme : jekyll-theme-minimal
show_downloads           : true

#show_downloads: true
#google_analytics:
#location: University of Warwick

