title: TWSH / Website
name: Tobias Slade-Harajda
logo: /assets/img/logo.png
description: 3rd year Ph.D. student
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
location: University of Warwick

